name: Run Unit Test

on:
  push:
    paths:
      - '3-implementando-o-solid/**'
  workflow_dispatch:

jobs:
  run-unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v3

      
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      
      - name: Debug - Check if package-lock.json exists
        run: |
            pwd
            ls -la ./3-implementando-o-solid/projeto-construido-em-aula-api-gym-pass/ | grep package
      
      - run: npm ci
        working-directory: ./3-implementando-o-solid/projeto-construido-em-aula-api-gym-pass

      
      - run: npm run test
        working-directory: ./3-implementando-o-solid/projeto-construido-em-aula-api-gym-pass
