name: Run E2E Tests

on:
  push:
    paths:
      - '3-implementando-o-solid/**'
  workflow_dispatch:

jobs:
  run-e2e-test:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: apisolid

    steps:
      # Coloca o código do projeto no ambiente
      - uses: actions/checkout@v3

      # Instala o Node no ambiente
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./3-implementando-o-solid/package-lock.json
      
      # Instala as dependências no diretório 3-implementando-o-solid
      - run: npm ci
        working-directory: ./3-implementando-o-solid

      # Executa os testes no diretório 3-implementando-o-solid
      - run: npm run test:e2e
        working-directory: ./3-implementando-o-solid
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"
